name: "Run License Update"
description: "Validates that all the licenses are up to date."

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-languages@main
      with:
        ruby: true
        node: true

    - name: Run license verify
      id: check_verify
      shell: bash
      run: |
        output=$($GITHUB_ACTION_PATH/../script/licenses --verify || 1)
        result=$?

        if [ $result -eq 0 ] ; then
          echo "All licenses are up to date!"
        else
          output=$($GITHUB_ACTION_PATH/../script/licenses --update || 1)
          result=$?

          if git diff-index --quiet HEAD --; then
            echo "There was an error generating files! Try running script/licenses --verify locally to see what's wrong."
            exit 1
          else
            echo "Licenses updated successfully!"
          fi
        fi

    - name: Commit licenses
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[auto-license]: Update license information"

        commit_user_name: Sisyphus
        commit_user_email: sisyphus@yetto.app
        commit_author: Sisyphus <sisyphus@yetto.app>
