name: "Run License Update"
description: "Validates that all the licenses are up to date."

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-languages@main
      with:
        ruby: true
        node: true

    - name: Run license verify
      id: check_verify
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/../script/licenses --verify

    - name: Run license update
      if: failure()
      shell: bash
      run: $GITHUB_ACTION_PATH/../script/licenses --update

    - name: Commit licenses
      if: success() || failure()
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[auto-license]: Update license information"

        commit_user_name: Sisyphus
        commit_user_email: sisyphus@yetto.app
        commit_author: Sisyphus <sisyphus@yetto.app>
