name: "Run License Update"
description: "Validates that all the licenses are up to date."

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-languages@main
      with:
        ruby: true
        node: true

    - name: Run license verify
      shell: bash
      run: $GITHUB_ACTION_PATH/../script/licenses --verify

    - name: Update licenses
      if: ${{ failure() }}
      uses: yettoapp/actions/run-license-update@main
