name: "Run License Update"
description: "Validates that all the licenses are up to date."
inputs:
  ruby:
    description: "Set up Ruby environment"
    default: "false"
  node:
    description: "Set up Node environment"
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-languages@main
      with:
        ruby: ${{ inputs.ruby }}
        node: ${{ inputs.node }}

    - name: Run license verify
      id: check_verify
      shell: bash
      run: |
        $GITHUB_ACTION_PATH/../script/licenses --verify && true

        if [ $? -eq 0 ] ; then
          echo "All licenses are up to date!"
        else
          $GITHUB_ACTION_PATH/../script/licenses --update && true

          if git diff-index --quiet HEAD --; then
            echo "There was an error generating files! Try running script/licenses --verify locally to see what's wrong."
            exit 1
          else
            echo "Licenses updated successfully!"
          fi
        fi

    - name: Commit licenses
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[auto-license]: Update license information"

        commit_user_name: Sisyphus
        commit_user_email: sisyphus@yetto.app
        commit_author: Sisyphus <sisyphus@yetto.app>
