name: "Run License Update"
description: "Validates that all the licenses are up to date."

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-languages@main
      with:
        ruby: true
        node: true

    - name: Run license verify
      id: check_verify
      shell: bash
      run: |
        output=$($GITHUB_ACTION_PATH/../script/licenses --verify 2>&1)
        status="$?"
        echo "${output}"
        if [[ "${status}" -ne 0 ]]; then
          echo "needs_verify=true" >> $GITHUB_OUTPUT
        else
          exit 0
        fi

    - name: Run license update
      if: ${{ steps.check_verify.outputs.needs_verify == 'true' }}
      shell: bash
      run: $GITHUB_ACTION_PATH/../script/licenses --update

    - name: Commit licenses
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[auto-license]: Update license information"

        commit_user_name: Sisyphus
        commit_user_email: sisyphus@yetto.app
        commit_author: Sisyphus <sisyphus@yetto.app>
