name: "Run License Update"
description: "Validates that all the licenses are up to date."

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-sisyphus@main

    - name: Run license update
      shell: bash
      run: script/licenses --update

    - name: Commit licenses
      shell: bash
      run: |
        git add .
        git commit -m "[auto-license]: Update license information" || true
        git push
