name: "Run License Update"
description: "Validates that all the licenses are up to date."

runs:
  using: "composite"
  steps:
    - name: Run license update
      shell: bash
      run: script/licenses --update

    - name: Commit licenses
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[auto-license]: Update license information"

        branch: license-update

        create_branch: true

        commit_user_name: Sisyphus
        commit_user_email: sisyphus@yetto.app
        commit_author: Sisyphus <sisyphus@yetto.app>
