name: "Run Sorbet Update"
description: "Validates that all the Sorbet types are up to date."

inputs:
  has_db:
    description: "Sets up any necesary database information"
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-languages@main
      with:
        ruby: true

    - if: ${{ inputs.has_db == 'true' }}
      name: Set up the Rails database for Tapioca DSL reflection/generation
      env:
        RAILS_ENV: development
      shell: bash
      run: |
        bin/rails db:create && bin/rails db:migrate

    - name: Update RBI files
      id: update
      shell: bash
      run:  $GITHUB_ACTION_PATH/../script/sorbet --update

    - name: Commit types
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[auto-rbi]: Update RBI files"

        commit_user_name: Sisyphus
        commit_user_email: sisyphus@yetto.app
        commit_author: Sisyphus <sisyphus@yetto.app>
