name: "Run Sorbet Update"
description: "Validates that all the Sorbet types are up to date."

inputs:
  setup-db:
    description: "Sets up any necesary database information"
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-languages@main
      with:
        ruby: true

    - uses: yettoapp/actions/setup-sisyphus@main

    - if: ${{ inputs.setup-db == 'true' }}
      name: Set up the Rails application for Tapioca DSL generation
      env:
        RAILS_ENV: development
      shell: bash
      run: |
        bin/rails db:create && bin/rails db:migrate

    - name: Update RBI files
      id: update
      shell: bash
      run: script/typecheck --update

    - name: Commit Sorbet
      shell: bash
      run: |
        git add .
        git commit -m "[auto-rbi]: Update RBI files" || true
        git push
