name: "Run Sorbet Update"
description: "Validates that all the Sorbet types are up to date."

inputs:
  setup-db:
    description: "Sets up any necesary database information"
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-languages@main
      with:
        ruby: true

    - if: ${{ inputs.setup-db == 'true' }}
      name: Set up the Rails application for Tapioca DSL generation
      env:
        RAILS_ENV: development
      shell: bash
      run: |
        bin/rails db:create && bin/rails db:migrate

    - name: Update RBI files
      id: update
      shell: bash
      run: script/typecheck --update

    - name: Commit licenses
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[auto-rbi]: Update RBI files"

        branch: sorbet-update

        create_branch: true

        commit_user_name: Sisyphus
        commit_user_email: sisyphus@yetto.app
        commit_author: Sisyphus <sisyphus@yetto.app>
