---
name: "Run the test suite"
description: "Based on the provided inputs, sets up the language environment dependencies and runs a test suite."
inputs:
  ruby-version:
    description: "Ruby version to use"
    default: "default"
  node:
    description: "Set up Node environment"
    default: "false"
  github_token:
    description: "The token used when calling GitHub API"
    required: true

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-languages@main
      with:
        ruby: true
        node: ${{ inputs.node }}

    - if: ${{ env.DATABASE_URL }}
      name: Set up the Rails database
      shell: bash
      run: |
        bundle exec rake db:create
        sudo apt-get -yqq install libpq-dev
        bundle exec rake db:test:prepare

    - if: ${{ env.DATABASE_URL }}
      name: Set up the Rails assets
      shell: bash
      run: |
        bundle exec rake assets:precompile

    - name: Run tests
      shell: bash
      run: |
        script/ci
      env:
        COVERAGE: "1"

    - if: ${{ inputs.system_tests == 'true' }}
      name: Run system tests
      shell: bash
      run: |
        script/test-system

    - name: Install helpers
      shell: bash
      run: |
        : Install helpers
        echo "$GITHUB_ACTION_PATH/bin" >> $GITHUB_PATH

    - name: Generate coverage report
      shell: bash
      id: coverage_report
      run: |
        coverage_report="$(bundle exec ruby $GITHUB_ACTION_PATH/helpers/report.rb || true)"

        echo "report<<EOF"$'\n'"$coverage_report"$'\n'EOF >> $GITHUB_OUTPUT

    - uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        lcov-file: coverage/lcov.info
        github-token: ${{ inputs.github_token }}
