name: Deploy repository to Fly.io
on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      fly_token:
        required: true
    inputs:
      target:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy app to Fly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.40
      - run: flyctl deploy --remote-only --vm-size=performance-2x -c vendor/fly/fly-${{ inputs.target }}.toml
        env:
          FLY_API_TOKEN: ${{ secrets.fly_token }}
