name: Deploy repository to Fly.io
on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      fly_token:
        required: true
    inputs:
      target:
        required: true
        type: string
      forced:
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    name: Fly
    runs-on: ubuntu-latest
    steps:
      - name: Start deployment
        uses: gjtorikian/deployments@support-more-deployments-logic
        id: deployment
        with:
          step: start
          token: ${{ secrets.gh_token }}
          env: ${{ inputs.target }}
          auto_merge: true
          required_contexts: ${{ inputs.forced == true && '' }}

      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.40
      - run: flyctl deploy --remote-only --vm-size=performance-2x -c vendor/fly/fly-${{ inputs.target }}.toml
        env:
          FLY_API_TOKEN: ${{ secrets.fly_token }}

      - name: update deployment status
        uses: gjtorikian/deployments@support-more-deployments-logic
        if: always()
        with:
          step: finish
          token: ${{ secrets.gh_token }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
