name: Security

on:
  workflow_call:
    secrets:
      token:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  bundle-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: yettoapp/actions/setup-languages@main
        with:
          ruby: true

      # Patch-level verification for bundler.
      - name: Run bundle-audit
        run: |
          bundle exec bundle-audit check --update

  brakeman: # A static analysis security vulnerability scanner for Ruby on Rails applications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: yettoapp/actions/pr-contains-files@main
        id: pr_contains_rb
        with:
          pr_number: ${{ github.event.number }}
          pattern: ".rb$|erb$"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Ruby
        if: ${{ steps.pr_contains_rb.outputs.exists == 'true' }}
        uses: yettoapp/actions/setup-languages@main
        with:
          ruby: true

      - name: brakeman report
        if: ${{ steps.pr_contains_rb.outputs.exists == 'true' }}
        run: |
          bundle exec brakeman --color -o /dev/stdout -o security-results.json
          cat security-results.json
