name: Test Docker build

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      fly_token:
        required: true
    inputs:
      app_name:
        description: "Name of the app to deploy"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.gh_token }}

      - uses: yettoapp/actions/setup-fly@main

      - name: Build production Dockerfile
        run: flyctl deploy --remote-only --build-only -a ${{ inputs.app_name }}-production -c vendor/fly/fly-production.toml
        env:
          FLY_API_TOKEN: ${{ secrets.fly_token }}
